Allow usage of mjs
ghost-fvtt/foundry-factory pull request #154
Opened 2022-03-08 07:16 UTC by DavidArchibald

I requested #131 in order to fix some problems with Yarn 2/3 and `cjs` but I recently found out that `mjs` may be a better solution.

2022-03-08 18:50 UTC, ghost91- requested changes

2022-03-08 18:50 UTC, ghost91- commented on .eslintrc.cjs
> +    extraFileExtensions: ['.cjs', '.mjs'],
this is not needed, is it? foundry-factory itself doesn't use `.mjs`.

2022-03-08 18:50 UTC, ghost91- commented on src/presets/ghost-gulp-rollup/ghost-gulp-rollup-preset.ts
> +      {
please revert these formatting changes. Applies to other reformatted objects, too.

2022-03-08 18:50 UTC, ghost91- commented on template/ghost-gulp-rollup/.eslintrc.cjs.njk
> +      files: ['./*.cjs', './*.mjs'],
This doesn't look right to me: In `.mjs` files, we shouldn't allow  var requires as they are es modules, so they should use import instead.

2022-03-10 06:58 UTC, DavidArchibald commented on template/ghost-gulp-rollup/.eslintrc.cjs.njk
> +      files: ['./*.cjs', './*.mjs'],
Ah I'd misunderstood what the template was doing trying to put `mjs` alongside `cjs`, good catch!

2022-03-10 07:00 UTC, DavidArchibald commented on .eslintrc.cjs
> +    extraFileExtensions: ['.cjs', '.mjs'],
I was undecided on whether to add this or not just because I didn't know if foundry-factory would want to be consistent with the templates it provides. I'll revert this.

2022-03-15 08:10 UTC, ghost91- approved these changes

2022-03-15 08:15 UTC, merged